// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.9.0
// source: shortUrl.proto

package shortUrl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Expiration    string                 `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateShortUrlRequest) Reset() {
	*x = GenerateShortUrlRequest{}
	mi := &file_shortUrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShortUrlRequest) ProtoMessage() {}

func (x *GenerateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*GenerateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortUrl_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateShortUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateShortUrlRequest) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

type GenerateShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Shortcode     string                 `protobuf:"bytes,2,opt,name=shortcode,proto3" json:"shortcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateShortUrlResponse) Reset() {
	*x = GenerateShortUrlResponse{}
	mi := &file_shortUrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShortUrlResponse) ProtoMessage() {}

func (x *GenerateShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShortUrlResponse.ProtoReflect.Descriptor instead.
func (*GenerateShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_shortUrl_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateShortUrlResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateShortUrlResponse) GetShortcode() string {
	if x != nil {
		return x.Shortcode
	}
	return ""
}

type HandleShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortcode     string                 `protobuf:"bytes,1,opt,name=shortcode,proto3" json:"shortcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleShortRequest) Reset() {
	*x = HandleShortRequest{}
	mi := &file_shortUrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleShortRequest) ProtoMessage() {}

func (x *HandleShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleShortRequest.ProtoReflect.Descriptor instead.
func (*HandleShortRequest) Descriptor() ([]byte, []int) {
	return file_shortUrl_proto_rawDescGZIP(), []int{2}
}

func (x *HandleShortRequest) GetShortcode() string {
	if x != nil {
		return x.Shortcode
	}
	return ""
}

type HandleShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleShortResponse) Reset() {
	*x = HandleShortResponse{}
	mi := &file_shortUrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleShortResponse) ProtoMessage() {}

func (x *HandleShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleShortResponse.ProtoReflect.Descriptor instead.
func (*HandleShortResponse) Descriptor() ([]byte, []int) {
	return file_shortUrl_proto_rawDescGZIP(), []int{3}
}

func (x *HandleShortResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HandleShortResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_shortUrl_proto protoreflect.FileDescriptor

const file_shortUrl_proto_rawDesc = "" +
	"\n" +
	"\x0eshortUrl.proto\x12\bshortUrl\"K\n" +
	"\x17GenerateShortUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"expiration\x18\x02 \x01(\tR\n" +
	"expiration\"L\n" +
	"\x18GenerateShortUrlResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1c\n" +
	"\tshortcode\x18\x02 \x01(\tR\tshortcode\"2\n" +
	"\x12HandleShortRequest\x12\x1c\n" +
	"\tshortcode\x18\x01 \x01(\tR\tshortcode\"C\n" +
	"\x13HandleShortResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\alongUrl\x18\x02 \x01(\tR\alongUrl2\xb5\x01\n" +
	"\bShortUrl\x12[\n" +
	"\x10GenerateShortUrl\x12!.shortUrl.GenerateShortUrlRequest\x1a\".shortUrl.GenerateShortUrlResponse\"\x00\x12L\n" +
	"\vHandleShort\x12\x1c.shortUrl.HandleShortRequest\x1a\x1d.shortUrl.HandleShortResponse\"\x00B\fZ\n" +
	"./shortUrlb\x06proto3"

var (
	file_shortUrl_proto_rawDescOnce sync.Once
	file_shortUrl_proto_rawDescData []byte
)

func file_shortUrl_proto_rawDescGZIP() []byte {
	file_shortUrl_proto_rawDescOnce.Do(func() {
		file_shortUrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortUrl_proto_rawDesc), len(file_shortUrl_proto_rawDesc)))
	})
	return file_shortUrl_proto_rawDescData
}

var file_shortUrl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shortUrl_proto_goTypes = []any{
	(*GenerateShortUrlRequest)(nil),  // 0: shortUrl.GenerateShortUrlRequest
	(*GenerateShortUrlResponse)(nil), // 1: shortUrl.GenerateShortUrlResponse
	(*HandleShortRequest)(nil),       // 2: shortUrl.HandleShortRequest
	(*HandleShortResponse)(nil),      // 3: shortUrl.HandleShortResponse
}
var file_shortUrl_proto_depIdxs = []int32{
	0, // 0: shortUrl.ShortUrl.GenerateShortUrl:input_type -> shortUrl.GenerateShortUrlRequest
	2, // 1: shortUrl.ShortUrl.HandleShort:input_type -> shortUrl.HandleShortRequest
	1, // 2: shortUrl.ShortUrl.GenerateShortUrl:output_type -> shortUrl.GenerateShortUrlResponse
	3, // 3: shortUrl.ShortUrl.HandleShort:output_type -> shortUrl.HandleShortResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortUrl_proto_init() }
func file_shortUrl_proto_init() {
	if File_shortUrl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortUrl_proto_rawDesc), len(file_shortUrl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortUrl_proto_goTypes,
		DependencyIndexes: file_shortUrl_proto_depIdxs,
		MessageInfos:      file_shortUrl_proto_msgTypes,
	}.Build()
	File_shortUrl_proto = out.File
	file_shortUrl_proto_goTypes = nil
	file_shortUrl_proto_depIdxs = nil
}
